# Generated by Django 4.1.5 on 2023-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(choices=[('Chica', 'Chica'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(choices=[('Chica', 'Chica'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sudadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(choices=[('Chica', 'Chica'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
