# Generated by Django 4.1.5 on 2023-01-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_chaleco_nombre_alter_playera_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chaleco',
            new_name='Productos',
        ),
        migrations.DeleteModel(
            name='Playera',
        ),
        migrations.DeleteModel(
            name='Sudadera',
        ),
    ]
