# Generated by Django 4.1.5 on 2023-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('longitud', models.IntegerField(max_length=15)),
                ('capacidad', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escuderias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=50)),
                ('año_de_fundacion', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pilotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('edad', models.IntegerField(max_length=2)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('apodo', models.CharField(max_length=70)),
            ],
        ),
    ]
