# Generated by Django 4.1.5 on 2023-01-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='longitud',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='escuderias',
            name='año_de_fundacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
