# Generated by Django 4.1.5 on 2023-01-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula_1', '0002_alter_circuitos_capacidad_alter_circuitos_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotos',
            name='apodo',
        ),
    ]
