# Generated by Django 4.1.5 on 2023-01-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula_1', '0003_remove_pilotos_apodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='capacidad',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='longitud',
            field=models.CharField(max_length=20),
        ),
    ]
