# Generated by Django 4.1.5 on 2023-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula_1', '0005_posicion_pilotos_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion_constructores_2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('equipo', models.CharField(max_length=20)),
                ('puntos', models.CharField(max_length=10)),
            ],
        ),
    ]
